---
title: "Untitled"
output: html_document
date: '2023-05-25'
---
#
```{r}
remove(list=ls())
Data<-read.csv(choose.files(),header = T,stringsAsFactors = T)

```

# Linear regression model
```{r}
lm<-lm(y~x2+x7+x8, data = Data)

```
# Anova
```{r}
anova(lm)

```
# Calculate t statistics for testing the hypotheses.
```{r}
summary(lm)

#Reject H0 for all x2,x7, and x8 since p-value <0.05. They are all signicant

```
#Calculat R^2 and R^2adj for this model
```{r}
data_fitted <- fitted(lm)
residuals <- residuals(lm)

ss_res <- sum(residuals^2)

data_mean <- mean(Data$y)
ss_total <- sum((Data$y - data_mean)^2)

r_squared <- 1- (ss_res/SS_total)
r_squared

#or

summary(lm)$r.squared


num_predictors <- length(lm$coefficients) - 1
sample_size <- length(Data$y)

adjusted_r_squared <- 1 - ((1 - r_squared) * (sample_size - 1)) / (sample_size - num_predictors - 1)
adjusted_r_squared

#or

summary(lm)$adj.r.squared


```

```{r}
confint(lm,level=0.95)

```
#(f)
```{r}
new_data <- data.frame(x2=2300,x7=56,x8=2100)

predict(lm,new_data,interval="confidence")


```
